### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by OfficialCRUGG** [statiohq/funk.js#3]
Whilst in the past, this repository used the *ws* npm package, it recently switched to use the browser's built-in "WebSocket" class which makes it compatible with browsers but also dropped NodeJS support, since that class does not exist in NodeJS.

For third-party use and easier testing of Funk, having NodeJS support would be very useful though, so a solution working in browsers and NodeJS is needed.

**Comment by marinofranz** [comment]
Pull request opened for this issue #4

**Comment by marinofranz** [comment]
Was not linked to pull request, so closing now
